### ISSUE TITLE
Error in total stocking sum for forest type

### ISSUE THREAD

**Issue by jacobf37** [Crghilardi/ForTyp#1]
In **forest_type.cpp** lines 647-649 where the total stocking is summed up the loop is getting each value from the stocking array `s` and then trying to use it as an index for the array.

`    //! TOTAL FOREST STOCKING (1-210)
for (auto i : s) {
        totstk += s[i];
    };`

Can be fixed with:
`    //! TOTAL FOREST STOCKING (1-210)
for (auto i : s) {
        totstk += i;
    };`

**Comment by Crghilardi** [comment]
Thanks for opening the issue! I pushed a commit on a new branch `issue-1` with the fix if you want to try it out. Everything builds and the demo still seems to work, I'll  PR and merge it in when I get a moment 

I think this was an artifact of me directly translating from the FORTRAN implementation and how that handles arrays
